### ISSUE TITLE
Could you host this example as gh-page?

### ISSUE THREAD

**Issue by madnight** [mobxjs/mobx-react-boilerplate#16]
People like me are happier when they are able to directly view the result without clone, npm install, ...

**Comment by SogoGolf** [comment]
i agree too. would greatly appreciate it if you could add a webpack PROD config that generated the index.html and let us deploy the site to gh-page, or firebase hosting, or...   this is quite confusing for those of us new to webpack 

many thanks.

**Comment by mweststrate** [comment]
To directly see a running app, check the code sandboxes linked in the mobx readme, for example: https://codesandbox.io/s/v3v0my2370
