### ISSUE TITLE
Update to React 16.x

### ISSUE THREAD

**Issue by micros123** [mobxjs/mobx-react-boilerplate#18]
It would be great if all libraries could be updated to the last major version. Or would you accept a Pull Request for this?

**Comment by baruchvlz** [comment]
You can just clone the repository and do `yarn && yarn upgrade`. These versions work fine

```json
  "dependencies": {
    "mobx": "^5.0.3",
    "mobx-react": "^5.2.3",
    "mobx-react-devtools": "^6.0.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
  }
```

**Comment by mweststrate** [comment]
Will update dependencies once we can use stage 2 decorators

Op wo 12 sep. 2018 om 12:40 schreef Baruch <notifications@github.com>:

**Comment by mweststrate** [comment]
This was fixed a while ago
