### ISSUE TITLE
why Tips me 'Cannot read property 'push' of undefined' ？

### ISSUE THREAD

**Issue by xulayen** [mobxjs/mobx-react-boilerplate#19]
import { observable, computed, action } from "mobx";

import TodoModel from "./TodoModel";

export default class TodoListModel {
  @observable todos = [];

  @computed 
  get unfinishedTodoCount() {
    return this.todos.filter(todo => !todo.finished).length;
  }

  @action
  addTodo(title) {
    this.todos.push(new TodoModel(title));
  }
}

**Comment by mweststrate** [comment]
Sounds like you are calling `addTodo` from a place where `this` is not correctly provided. Using `@action.bound` might solve your issue.
