### ISSUE TITLE
why tips me todo is not defined?

### ISSUE THREAD

**Issue by xulayen** [mobxjs/mobx-react-boilerplate#20]
import React, { Component } from "react";
import { observer } from "mobx-react";

@observer
export default class Todo extends Component {
    @observable todo = {};
    constructor(props) {
        super(props);
    }

    render(){
        <li>
            <input
            type="checkbox"
            checked={todo.finished}
            onClick={() => (todo.finished = !todo.finished)}
            />
            {todo.title}
        </li>
    }
}

**Comment by mweststrate** [comment]
Seems you need `this.todo`. But please file mobx related questions, not directly related to this boilerplate, at https://github.com/mobxjs/mobx/issues
