### ISSUE TITLE
Hot reloading not working properly

### ISSUE THREAD

**Issue by luandro** [mobxjs/mobx-react-boilerplate#6]
Just cloned the boilerplate, and it seems hot reloading isn't working properly:

```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR]  - 76
```

Any guesses? Maybe related to [this](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.h5zy8i66d)?

**Comment by mweststrate** [comment]
Yup, and see also this: https://github.com/mobxjs/mobx-react-typescript-boilerplate/issues/2

I'm gonna remove it from the boilerplates as it adds only confusion, although it works (mostly) in larger projects like https://github.com/mobxjs/mobx-reactive2015-demo
