### ISSUE TITLE
"Redux-like" Implementation

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx-react-boilerplate#8]
Hello.

I would like to create a "Redux-like" implementation for people coming from Redux.

__Important:__ I'm not trying to "teach" people to use MobX in a Redux way, MobX is great because it's different, it's easy to learn and simple to use. My "Redux-like" implementation is just a suggestion for people that already know Redux understand how to use MobX faster (like a MobX for Redux users tutorial).

Here is the first draft:

```js
import React, { Component, PropTypes } from 'react';
import { render } from 'react-dom';
import { observable } from 'mobx';
import { observer } from 'mobx-react';
import DevTools from 'mobx-react-devtools';

// Stores maintain state and methods are the actions that transforms it's state
// So a store is like a reducer and a store method is like an action
// You can still import other stores inside a store,
// e.g., you can use a NotificationStore inside an AuthStore
class TimerStore {
  @observable secondsElapsed;

  constructor(secondsElapsed = 0) {
    this.secondsElapsed = secondsElapsed;
  }

  tick = () => {
    this.secondsElapsed += 1;
  }

  reset = () => {
    this.secondsElapsed = 0;
  }
}

// "Smart" component
@observer
class TimerContainer extends Component {
  constructor(props) {
    super(props)
    this.store = new TimerStore(props.secondsElapsed)
  }

  render() {
    const { secondsElapsed, reset } = this.store
    return (
      <Timer
        secondsElapsed={secondsElapsed}
        onClick={reset}
      />
    )
  }

  componentDidMount = () => {
    this.interval = setInterval(this.store.tick, 1000);
  }

  componentWillUnmount = () => {
    clearInterval(this.interval);
  }
};

// "Dumb" component
function Timer({ secondsElapsed, onClick }) {
  return (
    <button onClick={onClick}>
      Seconds elapsed: {secondsElapsed}
    </button>
  )
}
Timer.propTypes = {
  secondsElapsed: PropTypes.number,
  onClick: PropTypes.func
}
Timer.defualtProps = {
  secondsElapsed: 0
}

// Another "dumb" component
function App() {
  return (
    <div>
      <TimerContainer secondsElapsed={10} />
      <DevTools />
    </div>
  )
}

render(<App />, document.getElementById('root'));
```

@gaearon thoughts?

**Comment by amsb** [comment]
I really like Redux and the ecosystem it spawned, but being explorative I experimented with using MobX to affect a different balance in the trade-off between explicit and implicit. Still experimental/work-in-progress, but you might be interested in taking a look at [mobx-reactor](https://github.com/amsb/mobx-reactor) as you grapple with how best to structure your own application(s).

**Comment by hnordt** [comment]
@amsb I think MobX is great because it's really simple, there aren't many new concepts.

I think we should not try to simulate a Redux environment with MobX, MobX is good because it's different, you can choose to be explicit or implicit.

Here is the way I like to implement MobX:

```js
// todoStore.js

class TodoStore {
  @observable todos = []

  getTodos = () => {
    return this.todos
  }

  getTodo = id => {
    return this.todos.find(todo => todo.id === id)
  }

  addTodo = text => {
    this.todos.push({ id: Date.now(), text })
  }

  removeTodo = id => {
    this.todos = this.todos.filter(todo => todo.id !== id)
  }
}

class ExplicitTodoStore {
  @observable todos = []

  getTodos = () => {
    return this.todos
  }

  getTodo = id => {
    return this.todos.find(todo => todo.id === id)
  }

  addTodo = text => {
    
  }

  removeTodo = id => {
    this.todos = this.todos.filter(todo => todo.id !== id)
  }
}

export default const todoStore = new TodoStore()

// then in my components I import todoStore and call it's methods
```

**Comment by crapthings** [comment]
@hnordt hey could u add some react example to this pls ?

// todoStore.js

class TodoStore {
  @observable todos = []

  getTodos = () => {
    return this.todos
  }

  getTodo = id => {
    return this.todos.find(todo => todo.id === id)
  }

  addTodo = text => {
    this.todos.push({ id: Date.now(), text })
  }

  removeTodo = id => {
    this.todos = this.todos.filter(todo => todo.id !== id)
  }
}

const todoStore = new TodoStore()

export default todoStore

// then in my components I import todoStore and call it's methods
// (instead passing it around through props, I just import it directly)
